#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wger"
name = "wger"
description.en = "Fitness, workout, nutrition and weight tracker"

version = "2.4~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://wger.de/"
admindoc = "https://wger.readthedocs.io/en/latest/"
userdoc = "https://wger.de/"
code = "https://github.com/wger-project/wger"
cpe = "cpe:2.3:a:wger:workout_manager"

fund = "https://buymeacoffee.com/wger"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "550M"
ram.build = "1G"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/wger-project/wger/archive/refs/tags/2.4.tar.gz"
    sha256 = "ccc91d1a948e29d985b0d0a72160ead2d6b10e1bc0ddf52e19dba7223d98c1ec"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3, python3-venv, ffmpeg, redis-server"
    
    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"

