#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wger"
name = "wger"
description.en = "Fitness, workout, nutrition and weight tracker"

version = "2.3~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://wger.de/"
admindoc = "https://wger.readthedocs.io/en/latest/"
userdoc = "https://wger.de/"
code = "https://github.com/wger-project/wger"
cpe = "cpe:2.3:a:wger:workout_manager"

fund = "https://buymeacoffee.com/wger"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/wger-project/wger/archive/b7a92641264cabbdb8008f9b8c6141683a5d7490.tar.gz"
    sha256 = "d9c611ab96efb18b52f5d99a269d1e04f867a734dd2cf6dcc7f4d812a2f529cb"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000

    [resources.apt]
    packages = [ "postgresql, postgresql-contrib, python3, python3-venv, ffmpeg, redis-server" ]
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
