#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_app_setting_set_default --key=secret_key --value=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set_default --key=signing_key --value=$(ynh_string_random --length=45 | base64)

# Remove this key because it has been renamed for v2.4
ynh_app_setting_delete --key=key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
chown -R "$app":www-data "$install_dir"/

#=================================================
# UPGRADE PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading Python dependencies..."

mkdir -p "$data_dir/media"
mkdir -p "$install_dir/static"

chown -R "$app:$app" "$data_dir/media"
chown -R "$app:$app" "$install_dir/static"

pushd "$install_dir"/
    export PYTHONPATH=$install_dir
    
    export MEDIA_ROOT=$data_dir/media
    export STATIC_ROOT=$install_dir/static
    
    export DJANGO_DB_ENGINE=django.db.backends.postgresql
    export DJANGO_DB_DATABASE=$db_name
    export DJANGO_DB_USER=$db_user
    export DJANGO_DB_PASSWORD=$db_pwd
    export DJANGO_DB_HOST=localhost
    export DJANGO_DB_PORT=5432

    export ALLOWED_HOSTS=$domain

    ynh_script_progression "Creating venv..."
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip gunicorn
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install .

    ynh_script_progression "Configuring $app..."
    ynh_hide_warnings corepack enable
    ynh_hide_warnings npm install -g corepack@latest
    ynh_hide_warnings ynh_exec_as_app corepack prepare yarn@4 --activate
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" npm install sass

    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/wger" bootstrap
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/python" manage.py collectstatic --noinput --verbosity 2
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/python" manage.py migrate

	echo "from django.contrib.sites.models import Site; site = Site.objects.get(pk=1); site.domain = '$domain'; site.name = '$domain wger Workout Manager'; site.save()" | ynh_hide_warnings "$install_dir/venv/bin/python" "$install_dir/manage.py" shell
	echo "yes"
 
    ynh_safe_rm "$install_dir/.cache/pip"
popd

chown -R "$app:www-data" "$install_dir"

ynh_config_add_logrotate

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="$app service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
