#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
python_version=3.12

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_app_setting_set_default --key=secret_key --value=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set_default --key=signing_key --value=$(ynh_string_random --length=45 | base64)

# Remove this key because it has been renamed for v2.4
ynh_app_setting_delete --key=key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
chown -R "$app":www-data "$install_dir"/

#=================================================
# UPGRADE PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading Python dependencies..."


export PATH="$install_dir/.uv:$PATH"
export UV_PYTHON_INSTALL_DIR="$install_dir/.python_runtime"
export UV_CACHE_DIR="$install_dir/.uv_cache"

mkdir -p "$data_dir/media"
mkdir -p "$install_dir/static"

chown -R "$app:$app" "$data_dir/media"
chown -R "$app:$app" "$install_dir/static"


ynh_hide_warnings uv sync --frozen --no-group dev --group docker --python $python_version --project "$install_dir" 

pushd "$install_dir"/

    ynh_script_progression "Configuring $app..."
    ynh_hide_warnings corepack enable
    ynh_hide_warnings npm install -g corepack@latest
    ynh_hide_warnings ynh_exec_as_app corepack prepare yarn@4 --activate
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" npm install sass


    set -a

    source $install_dir/.env

    ynh_hide_warnings "$install_dir/.venv/bin/wger" bootstrap
    ynh_hide_warnings "$install_dir/.venv/bin/python" manage.py collectstatic --noinput --verbosity 2
    ynh_hide_warnings "$install_dir/.venv/bin/python" manage.py migrate

    echo "from django.contrib.sites.models import Site; site = Site.objects.get(pk=1); site.domain = '$domain'; site.name = '$domain wger Workout Manager'; site.save()" | ynh_hide_warnings "$install_dir/.venv/bin/python" "$install_dir/manage.py" shell
	echo "yes"
 
    set +a

    ynh_safe_rm "$install_dir/.cache/pip"
popd

chown -R "$app:www-data" "$install_dir"

ynh_config_add_logrotate

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="$app service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
